@echo off
start /D "lelun" lelun_arrang_three.bat
start /D "lelun" lelun_run_arrang_five.bat
start /D "lelun" lelun_run_gd11x5.bat
start /D "lelun" lelun_run_gx11x5.bat
start /D "lelun" lelun_run_haobc.bat
start /D "lelun" lelun_run_haobcA.bat
start /D "lelun" lelun_run_lottery.bat
start /D "lelun" lelun_run_paintball.bat
start /D "lelun" lelun_run_paintballA.bat
start /D "lelun" lelun_run_sd11x5.bat
start /D "lelun" lelun_run_SevenColor.bat
start /D "lelun" lelun_run_single_basketball.bat
start /D "lelun" lelun_run_single_basketballA.bat
start /D "lelun" lelun_Single_thread_scene.bat
start /D "lelun" lelun_SingleFoot.bat
start /D "lelun" lelun_SingleFootA.bat
start /D "lelun" lelun_three_D.bat
start /D "lelun" lelun_UnionLotto.bat
start /D "lelun" lelun_run_RX9C.bat
start /D "lelun" lelun_run_SF14C.bat