@echo off
start /D "lemi" lemi_run_arrang_three.bat
start /D "lemi" lemi_run_arrang_five.bat
start /D "lemi" lemi_run_gd11x5.bat
start /D "lemi" lemi_run_gx11x5.bat
start /D "lemi" lemi_run_haobc.bat
start /D "lemi" lemi_run_haobcA.bat
start /D "lemi" lemi_run_lottery.bat
start /D "lemi" lemi_run_paintball.bat
start /D "lemi" lemi_run_paintballA.bat
start /D "lemi" lemi_run_sd11x5.bat
start /D "lemi" lemi_run_SevenColor.bat
start /D "lemi" lemi_run_single_basketball.bat
start /D "lemi" lemi_run_single_basketballA.bat
start /D "lemi" lemi_Single_thread_scene.bat
start /D "lemi" lemi_SingleFoot.bat
start /D "lemi" lemi_SingleFootA.bat
start /D "lemi" lemi_three_D.bat
start /D "lemi" lemi_UnionLotto.bat
start /D "lemi" lemi_run_RX9C.bat
start /D "lemi" lemi_run_SF14C.bat