@echo off
start /D "leyou" leyou_arrang_three.bat
start /D "leyou" leyou_run_arrang_five.bat
start /D "leyou" leyou_run_gd11x5.bat
start /D "leyou" leyou_run_gx11x5.bat
start /D "leyou" leyou_run_haobc.bat
start /D "leyou" leyou_run_haobcA.bat
start /D "leyou" leyou_run_lottery.bat
start /D "leyou" leyou_run_paintball.bat
start /D "leyou" leyou_run_paintballA.bat
start /D "leyou" leyou_run_SevenColor.bat
start /D "leyou" leyou_run_single_basketball.bat
start /D "leyou" leyou_run_single_basketballA.bat
start /D "leyou" leyou_Single_thread_scene.bat
start /D "leyou" leyou_SingleFoot.bat
start /D "leyou" leyou_SingleFootA.bat
start /D "leyou" leyou_three_D.bat
start /D "leyou" leyou_UnionLotto.bat
start /D "leyou" leyou_run_RX9C.bat
start /D "leyou" leyou_run_SF14C.bat